#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 17 16:23:05 CST 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 3767b0d1d93c49e1ada8ae72b3981caa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mux_2x1_tb_behav xil_defaultlib.mux_2x1_tb -log elaborate.log"
xelab -wto 3767b0d1d93c49e1ada8ae72b3981caa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mux_2x1_tb_behav xil_defaultlib.mux_2x1_tb -log elaborate.log

